### PR TITLE
Add support for Wiki Loves Africa

### PR DESCRIPTION
**Pull request by JeanFred**
Since this was requested by @ezachte (on-wiki), I decided to give this a go :) I may have missed things of course ; it does work locally inside a Docker container.

Hope that helps!

(Before deploying, the WLdata module should be seeded.)

### CODE REVIEW

**Comment by ezachte** [comment]
Wow, thich is really awesome! Thanks a lot. J

 

I will start soon to add config data for WLA to 

https://commons.wikimedia.org/wiki/Module:WL_data

 

Cheers,

Erik

**Comment by ezachte** [comment]
Done. 

 

I added all African countries, with UTC diffs, and contest periods for WLA 2014,2015,2016.

2014 and 2105 ran from begin Oct to end Nov

2016 runs from begin Dec to end Jan 

 

Cheers,

Erik

 

From: Erik Zachte [mailto:erikzachte@infodisiac.com] 
Sent: Tuesday, January 10, 2017 21:41
To: 'ptwikis/wikiloves'; 'ptwikis/wikiloves'
Cc: 'Mention'
Subject: RE: [ptwikis/wikiloves] Add support for Wiki Loves Africa (#4)

 

Wow, thich is really awesome! Thanks a lot. J

 

I will start soon to add config data for WLA to 

https://commons.wikimedia.org/wiki/Module:WL_data

 

Cheers,

Erik

**Comment by danilomac** [comment]
Hi @JeanFred and @ezachte.
Jean, Sorry but I don't have time to work on this, if you find this code is stable I can merge it, but I can not develop the missing things and fix eventual bugs.
I developed the tool direct in Tool Labs login using vim, you can do the same to test the code while developing.

**Comment by JeanFred** [comment]
@danilomac Sure, I’m happy to be accountable on bug fixing if I break things. Note that I reproduced the prod environment inside a Docker container and can thus vouch that this code is working.

Shall I keep working in my fork and deploy the fork to Labs then?

**Comment by danilomac** [comment]
@JeanFred yes, you are free to deploy it to Labs.

**Comment by JeanFred** [comment]
@danilomac Thanks! Just for clarification − are you ok with me deploying it to https://tools.wmflabs.org/wikiloves − with the understanding that I will fix any outstanding issue that may arise − or would you prefer me to create another Labs?

**Comment by danilomac** [comment]
@JeanFred yes, you can deploy direct to https://tools.wmflabs.org/wikiloves

**Comment by JeanFred** [comment]
I now maintain this in my fork

**Pull request closed without merging**
